services:
  backend:
    build: ./backend
    environment:
      OSRM_URL: http://router.project-osrm.org
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
